// <auto-generated />
using System;
using HerosData.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HerosData.Migrations
{
    [DbContext(typeof(SuperHeroContext))]
    [Migration("20210210044611_navigationProperty")]
    partial class navigationProperty
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("HerosData.Entities.SuperHero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .UseIdentityColumn();

                    b.Property<string>("Hideout")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RealName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("WorkName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("superhero");
                });

            modelBuilder.Entity("HerosData.Entities.SuperPower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Ownerid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Ownerid")
                        .IsUnique()
                        .HasFilter("[Ownerid] IS NOT NULL");

                    b.ToTable("SuperPowers");
                });

            modelBuilder.Entity("HerosData.Entities.SuperPower", b =>
                {
                    b.HasOne("HerosData.Entities.SuperHero", "Owner")
                        .WithOne("SuperPower")
                        .HasForeignKey("HerosData.Entities.SuperPower", "Ownerid");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("HerosData.Entities.SuperHero", b =>
                {
                    b.Navigation("SuperPower");
                });
#pragma warning restore 612, 618
        }
    }
}
